### ISSUE TITLE
img ipv image

### ISSUE THREAD

**Issue by Demivdm** [Abeeryu/fix-the-flow-wireflow#3]
De image tag schrijf je normaal als img. Je kan ook de img tag nog afsluiten om het de code te verbeteren

https://github.com/Abeeryu/fix-the-flow-wireflow/blob/d5fde07b18290f4329eac1dd49b8329a20d445fa/index.html#L14

**Comment by Abeeryu** [comment]
Opgelost!

![Screenshot 2023-12-14 232025](https://github.com/Abeeryu/fix-the-flow-wireflow/assets/144008500/cd40cb65-372e-4c26-bd93-f36748d93f78)
