### ISSUE TITLE
Document language EN

### ISSUE THREAD

**Issue by TessaViergever** [Abeeryu/fix-the-flow-wireflow#5]
https://github.com/Abeeryu/fix-the-flow-wireflow/blob/d5fde07b18290f4329eac1dd49b8329a20d445fa/index.html#L2

Hi 😊

Ik zie dat je als document taal EN hebt ingesteld, de rest van je document is in het NL. Daarom zou ik ervoor kiezen om de taal van je document als NL in te stellen.

Hier een linkje met info:
https://www.w3.org/International/questions/qa-html-language-declarations

**Comment by Abeeryu** [comment]
Opgelost!

![Screenshot 2023-12-14 231734](https://github.com/Abeeryu/fix-the-flow-wireflow/assets/144008500/908c3856-bdd2-4657-80d9-d714ba7a7656)
